branch-defaults:
  master:
    environment: wrtc-env
    group_suffix: null
global:
  application_name: wrtc
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
